# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: Route
email: info@route.nyc
description: >- # this means to ignore newlines until "baseurl:"
  Route is a team of designers, developers, and cartographers who are dedicated to improving 
  mobility. We use our combined expertise to give cities adaptable tools to set residents and 
  visitors in motion.
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com
twitter_username: jekyllrb
github_username:  jekyll

# Build settings
markdown: kramdown
theme: minima
plugins:
  - jekyll-feed

exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules

collections:
  sections:
    output: false
  bios:
    output: false
  projects:
    output: false
  projectslides:
    output: false
  testimonials:
    output: false

prose:
  metadata:
    _testimonials:
    - name: "name"
      field:
        element: "text"
        label: "name"
    - name: "jobtitle"
      field:
        element: "text"
        label: "job title"
    - name: "order"
      field:
        element: "number"
        label: "order"
        value: 1
